services:
  angular:
    build:
      context: .
      target: dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - dev

  web:
    build:
      context: .
      target: prod
    ports:
      - "80:80"
    profiles:
      - prod
